table_config:
  table_name: "train_tickets_raw"
  engine: "MergeTree()"
  order_by:
    - "timestamp"
    - "route_id"
    - "train_id"
    - "departure_datetime"
  partition_by: toYYYYMM(timestamp)
  fields:
    - name: "timestamp"
      field_type: "DateTime"
    - name: "scrape_id"
      field_type: "String"
    - name: "route_id"
      field_type: "String"
    - name: "origin"
      field_type: "String"
    - name: "destination"
      field_type: "String"
    - name: "train_id"
      field_type: "INT"
    - name: "departure_datetime"
      field_type: "DateTime"
    - name: "arrival_datetime"
      field_type: "DateTime"
    - name: "provider"
      field_type: "INT"
    - name: "providerName"
      field_type: "String"
    - name: "corporationID"
      field_type: "INT"
    - name: "corporationName"
      field_type: "String"
    - name: "source_url"
      field_type: "String"
    - name: "price"
      field_type: "INT"
    - name: "available_seats"
      field_type: "INT"
    - name: "compartment_capacity"
      field_type: "INT"