table_config:
  table_name: "flight_tickets_raw"
  engine: "MergeTree()"
  order_by:
    - "timestamp"
    - "route_id"
    - "airline_code"
    - "departure_datetime"
  partition_by: toYYYYMM(timestamp)
  fields:
    - name: "timestamp"
      field_type: "DateTime"
    - name: "scrape_id"
      field_type: "String"
    - name: "route_id"
      field_type: "String"
    - name: "origin"
      field_type: "String"
    - name: "destination"
      field_type: "String"
    - name: "flight_id"
      field_type: "String"
    - name: "score"
      field_type: "Nullable(Float64)"
    - name: "journey_time"
      field_type: "String"
    - name: "flight_number"
      field_type: "String"
    - name: "airline_code"
      field_type: "String"
    - name: "airline_name"
      field_type: "String"
    - name: "airline_logo"
      field_type: "String"
    - name: "departure_terminal"
      field_type: "Nullable(String)"
    - name: "departure_datetime"
      field_type: "Nullable(String)"
    - name: "flight_status"
      field_type: "Nullable(String)"
    - name: "aircraft_title"
      field_type: "Nullable(String)"
    - name: "aircraft_short_title"
      field_type: "Nullable(String)"
    - name: "aircraft_score"
      field_type: "Nullable(Float64)"
    - name: "source_url"
      field_type: "String"
    - name: "available_seats"
      field_type: "INT"
    - name: "booking_class"
      field_type: "String"
    - name: "price"
      field_type: "INT"
    - name: "discount"
      field_type: "Nullable(Float64)"
    - name: "discount_percent"
      field_type: Nullable(Float64)