clickhouse:
  host: "localhost"
  port: 9000
  user: "admin"
  password: "password"
  database: "ticket_pricing"

routes:
  - origin:
      name: "THR"
      codes:
          mrbilit_trains: 1
    destination:
      name: "MHD"
      codes:
        mrbilit_trains: 191
    reverse: true


departure_windows: [0, 1, 2, 3, 4, 5, 6, 7, 14, 30, 60, 90]  # days ahead

collection:
  rate_limit_delay: 2  # seconds between requests
  max_retries: 3


sources:
  mrbilit_flights:
    vehicle: plane
    url: "https://flight.atighgasht.com/api/Flights"
    headers:
      Accept: "application/json, text/plain, */*"
      Accept-Language: "en-GB,en-US;q=0.9,en;q=0.8"
      Content-Type: "application/json"
      origin: 'https://mrbilit.com'
      priority: 'u=1, i'
      referer: 'https://mrbilit.com/'
      sec-ch-ua: '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"'
      sec-ch-ua-mobile: '?0'
      sec-ch-ua-platform: '"Linux"'
      sec-fetch-dest: 'empty'
      sec-fetch-mode: 'cors'
      sec-fetch-site: 'cross-site'
      sessionid: 'session_2388840d-d921-462f-9b6c-5f67b97e41d0'
      user-agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36'
      x-playerid: 'ccd3545f-0a66-4574-a184-ffc1f82ec8fd'

    default_payload:
      AdultCount: 1
      ChildCount: 0
      InfantCount: 0
      CabinClass: "All"
      Baggage: true
      IncludeFlightsWithHigherCapacity: false
  